"""Initial migration

Revision ID: 5cf463c9b90e
Revises: 
Create Date: 2026-01-11 00:15:56.343043

"""
from sqlalchemy.sql.sqltypes import Text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5cf463c9b90e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('encryption_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reactions', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('read_by', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_messages_is_read')
        batch_op.drop_index('ix_messages_sent_at')
        batch_op.create_foreign_key(None, 'messages', ['reply_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])
        batch_op.drop_column('read_at')
        batch_op.drop_column('message_body')
        batch_op.drop_column('subject')
        batch_op.drop_column('sender_type')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('is_read')
        batch_op.drop_column('attachments')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('socket_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('socket_id')
        batch_op.drop_column('is_online')
        batch_op.drop_column('avatar')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sender_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('message_body', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('read_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_messages_sent_at', ['sent_at'], unique=False)
        batch_op.create_index('ix_messages_is_read', ['is_read'], unique=False)
        batch_op.alter_column('application_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('read_by')
        batch_op.drop_column('status')
        batch_op.drop_column('reply_to_id')
        batch_op.drop_column('reactions')
        batch_op.drop_column('encryption_key')
        batch_op.drop_column('is_encrypted')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_url')
        batch_op.drop_column('message_type')
        batch_op.drop_column('content')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
